In [1]:
using MAT
using DataStructures
using LinearAlgebra

# Matrices

We load the precomputed matrices from MATLAB.

In [2]:
adjacency_file = matopen("./matrices/adjacency-reduced.mat")
cluster1_file = matopen("./matrices/S1-reduced.mat")
cluster2_file = matopen("./matrices/S2-reduced.mat")
cluster3_file = matopen("./matrices/S3-reduced.mat")

MAT.MAT_v5.Matlabv5File(IOStream(<file ./matrices/S3-reduced.mat>), false, #undef)

In [3]:
S = read(adjacency_file, "S")
G1 = read(cluster1_file, "S1")
G2 = read(cluster2_file, "S2")
G3 = read(cluster3_file, "S3")

s_dim = size(S)
g1_dim = size(G1)
g2_dim = size(G2)
g3_dim = size(G3)

println("Matrix dimensions:")
println("\t[S] Adjacency matrix: ", s_dim)
println("\t[G1] Cluster 1: ", g1_dim)
println("\t[G2] Cluster 2: ", g2_dim)
println("\t[G3] Cluster 3: ", g3_dim)

Matrix dimensions:
	[S] Adjacency matrix: (31, 31)
	[G1] Cluster 1: (13, 13)
	[G2] Cluster 2: (12, 12)
	[G3] Cluster 3: (6, 6)


## Adjacency Submatrices $W_{vp}$

$W_{vp}$ is the submatrix of size $m_v \times m_p$ consisting of all interactions between $G_p$ and $G_v$.

($m_i$ is the size of the group $i$)

$$W_{12}$$

In [4]:
row_start = g1_dim[1]+1
row_end = g1_dim[1] + g2_dim[1]
col_start = 1
col_end = g1_dim[2]
W12 = S[row_start:row_end, col_start:col_end]

12×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{21}$$

In [5]:
row_start = 1
row_end = g1_dim[1]
col_start = g1_dim[2] + 1                            # Same column range as W12
col_end = col_start -1 + g2_dim[2]
W21 = S[row_start:row_end, col_start:col_end]

13×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [12]:
W12 == W21'

true

$$W_{13}$$

In [6]:
row_start = g1_dim[1] + g2_dim[1] +1
row_end = g1_dim[1] + g2_dim[1] + g3_dim[1]
col_start = 1
col_end = g1_dim[2]
W13 = S[row_start:row_end, col_start:col_end]

6×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{31}$$

In [13]:
W31 = W13'
W31

13×6 adjoint(::Matrix{Float64}) with eltype Float64:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

$$W_{23}$$

In [7]:
row_start = g1_dim[1] + g2_dim[1] +1
row_end = g1_dim[1] + g2_dim[1] + g3_dim[1]
col_start = g1_dim[2]+1
col_end = g1_dim[2] + g2_dim[2]
W23  = S[row_start:row_end, col_start:col_end]

6×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{32}$$

In [14]:
W32 = W23'
W32

12×6 adjoint(::Matrix{Float64}) with eltype Float64:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0

## Global Diagonal In-Degree Submatrix

In [8]:
K = [[sum(W12 .== 1),0,0] [0,sum(W13 .== 1),0] [0,0,sum(W23 .== 1)]]

3×3 Matrix{Int64}:
 7  0  0
 0  0  0
 0  0  2

## Compatibility Equations

$$W_{vp}^\prime \hat a_v= \lambda_{vp}^\prime\hat a_p$$
we focus on fixed $v$, variable $p$.

$$W^\prime_{vp} = W^T_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad W^\prime_{vp} = W^T_{pv}W^T_{vp}\quad \text{ if }\quad v\ne p$$
$$\lambda^\prime_{vp} = \lambda_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad \lambda^\prime_{vp} = \lambda_{pv}\lambda_{vp}\quad \text{ if }\quad v\ne p$$

In [17]:
W11p = G1'
W12p = W12' * W21'
W21p = W21' * W12'
W31p = W31' * W13'
W22p = G2'
W23p = W23' * W32'
W32p = W32' * W23'
W13p = G3'

6×6 adjoint(::Matrix{Float64}) with eltype Float64:
 0.0  1.0  0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  1.0  1.0  0.0
 0.0  0.0  1.0  0.0  1.0  0.0
 1.0  1.0  1.0  1.0  0.0  1.0
 0.0  0.0  0.0  0.0  1.0  0.0

In [18]:
function dominant_eigenpair(A)
    v = eigen(A)
    eigenvalues = v.values
    eigenvectors = v.vectors
    max_eigenvalue = maximum(abs.(eigenvalues))
    max_eigenvalue_index = argmax(abs.(eigenvalues))
    max_eigenvector = eigenvectors[:, max_eigenvalue_index]
    return (max_eigenvalue, max_eigenvector)
end

# Eigenvalues
λ11, v11 = dominant_eigenpair(W11p)

λ22, v22 = dominant_eigenpair(W22p)

λ33, v33 = dominant_eigenpair(W33p)

λ12 = eigmax(W12p) * eigmax(W12p)
λ13 = eigmax(W13p) * eigmax(W13p)
λ23 = eigmax(W23p) * eigmax(W23p)

println("λ₁₁: ", λ11)
println("v11: ", v11)

println("λ₂₂: ", λ22)
println("v22: ", v22)

println("λ₃₃: ", λ33)
println("v33: ", v33)

println("λ₁₂: ", λ12)
println("λ₁₃: ", λ13)
println("λ₂₃: ", λ23)

λ₁₁: 3.4203762111170875
v11: [-0.1719389806589758, -0.12072895324281166, -0.17331904636202894, -0.17331904636202894, -0.12072895324281165, -0.24099945900580494, -0.4208773624512082, -0.4208773624512082, -0.2409994590058049, -0.31655996799094643, -0.24610004074010916, -0.3165599679909463, -0.38701989524178493]
λ₂₂: 4.694988076660711
v22: [0.06177615655203378, -0.33155016957185446, -0.22158539019499796, -0.27625513556913817, -0.33155016957185446, 0.2596095253413012, 0.36564611534649305, 0.36564611534649305, -0.29003831843372513, -0.2657249684875209, 0.3090485342347392, 0.2566738026856661]
λ₃₃: 2.7092753594369228
v33: [-0.3696193697696122, -0.3696193697696122, -0.3696193697696122, -0.3696193697696122, -0.6317812811178026, -0.23319197840750588]
λ₁₂: 1.0
λ₁₃: 7.340172973252065
λ₂₃: 1.0


$$\hat a_v= x_1u_1+\dots+x_ru_r$$
$$\{u_i\}\in\mathbb R^{m_v}$$
$$m_v = |G_p|$$

$$\hat{\mathbf{C}}\ \mathbf y = (0,\dots,0,1)^T$$
$$\mathbf{y}:=(x_1,\ \dots\ ,\ x_r,\ K)$$
$$\hat{\mathbf C}=\left(\frac{C}{1^{T}}\frac{-1}{0}\right)$$
$$C=(c_{st})_{s,t} \quad\text{ is }\quad r\times r$$

$$c_{st}:=\sum_{p=1}^n\langle W^\prime_{vp} u_s- \lambda^\prime_{vp} u_s,\ W^\prime_{vp} u_t- \lambda^\prime_{vp} u_t\rangle$$

A solution that is not restricted to a particular subspace is obtained when $r = m_v$ and $u_1,\dots, u_{m_v}$ is the canonical basis of $\mathbb R^{m_v}$. This solution is the one with the smallest error.

In [19]:
# CLUSTER 1

# canonical basis
canonical_basis = Diagonal(ones(13))

e1 = canonical_basis[:,1]
e2 = canonical_basis[:,2]
e3 = canonical_basis[:,3]
e4 = canonical_basis[:,4]
e5 = canonical_basis[:,5]
e6 = canonical_basis[:,6]
e7 = canonical_basis[:,7]
e8 = canonical_basis[:,8]
e9 = canonical_basis[:,9]
e10 = canonical_basis[:,10]
e11 = canonical_basis[:,11]
e12 = canonical_basis[:,12]
e13 = canonical_basis[:,13]

u = [e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 e12 e13]

# Matrix C
r = 13
C = zeros(r,r)

# Loop over each element of the matrix and calculate the inner product
for s in 1:r
  for t in 1:r
    C[s,t] = dot(W11p * u[s] .- λ11 * u[s], W11p * u[t] .- λ11 * u[t])
                + dot(W12p * u[s] .- λ12 * u[s], W12p * u[t] .- λ12 * u[t])
                + dot(W13p * u[s] .- λ13 * u[s], W13p * u[t] .- λ13 * u[t])
  end
end

C

13×13 Matrix{Float64}:
 1743.5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0