In [1]:
using MAT
using DataStructures
using LinearAlgebra

# Matrices

We load the precomputed matrices from MATLAB.

In [2]:
adjacency_file = matopen("./matrices/adjacency-reduced.mat")
cluster1_file = matopen("./matrices/S1-reduced.mat")
cluster2_file = matopen("./matrices/S2-reduced.mat")
cluster3_file = matopen("./matrices/S3-reduced.mat")

MAT.MAT_v5.Matlabv5File(IOStream(<file ./matrices/S3-reduced.mat>), false, #undef)

In [3]:
S = read(adjacency_file, "S")
G1 = read(cluster1_file, "S1")
G2 = read(cluster2_file, "S2")
G3 = read(cluster3_file, "S3")

s_dim = size(S)
g1_dim = size(G1)
g2_dim = size(G2)
g3_dim = size(G3)

println("Matrix dimensions:")
println("\t[S] Adjacency matrix: ", s_dim)
println("\t[G1] Cluster 1: ", g1_dim)
println("\t[G2] Cluster 2: ", g2_dim)
println("\t[G3] Cluster 3: ", g3_dim)

Matrix dimensions:
	[S] Adjacency matrix: (31, 31)
	[G1] Cluster 1: (13, 13)
	[G2] Cluster 2: (12, 12)
	[G3] Cluster 3: (6, 6)


## Adjacency Submatrices $W_{vp}$

$W_{vp}$ is the submatrix of size $m_v \times m_p$ consisting of all interactions between $G_p$ and $G_v$.

($m_i$ is the size of the group $i$)

$$W_{12}$$

In [4]:
row_start = g1_dim[1]+1
row_end = g1_dim[1] + g2_dim[1]
col_start = 1
col_end = g1_dim[2]
W12 = S[row_start:row_end, col_start:col_end]

12×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{21}$$

In [5]:
row_start = 1
row_end = g1_dim[1]
col_start = g1_dim[2] + 1                            # Same column range as W12
col_end = col_start -1 + g2_dim[2]
W21 = S[row_start:row_end, col_start:col_end]

13×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [6]:
W12 == W21'

true

$$W_{13}$$

In [7]:
row_start = g1_dim[1] + g2_dim[1] +1
row_end = g1_dim[1] + g2_dim[1] + g3_dim[1]
col_start = 1
col_end = g1_dim[2]
W13 = S[row_start:row_end, col_start:col_end]

6×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{31}$$

In [8]:
W31 = W13'
W31

13×6 adjoint(::Matrix{Float64}) with eltype Float64:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

$$W_{23}$$

In [9]:
row_start = g1_dim[1] + g2_dim[1] +1
row_end = g1_dim[1] + g2_dim[1] + g3_dim[1]
col_start = g1_dim[2]+1
col_end = g1_dim[2] + g2_dim[2]
W23  = S[row_start:row_end, col_start:col_end]

6×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{32}$$

In [10]:
W32 = W23'
W32

12×6 adjoint(::Matrix{Float64}) with eltype Float64:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0

## Global Diagonal In-Degree Submatrix

In [11]:
K = [[sum(W12 .== 1),0,0] [0,sum(W13 .== 1),0] [0,0,sum(W23 .== 1)]]

3×3 Matrix{Int64}:
 7  0  0
 0  0  0
 0  0  2

## Compatibility Equations

$$W_{vp}^\prime \hat a_v= \lambda_{vp}^\prime\hat a_p$$
we focus on fixed $v$, variable $p$.

$$W^\prime_{vp} = W^T_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad W^\prime_{vp} = W^T_{pv}W^T_{vp}\quad \text{ if }\quad v\ne p$$
$$\lambda^\prime_{vp} = \lambda_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad \lambda^\prime_{vp} = \lambda_{pv}\lambda_{vp}\quad \text{ if }\quad v\ne p$$

In [12]:
W11p = G1'
W12p = W12' * W21'
W21p = W21' * W12'
W13p = W13' * W31'
W31p = W31' * W13'
W22p = G2'
W23p = W23' * W32'
W32p = W32' * W23'
W33p= G3'

println(size(W11p))
println(size(W22p))
println(size(W33p))

(13, 13)
(12, 12)
(6, 6)


In [13]:
function dominant_eigenpair(A)
    v = eigen(A)
    eigenvalues = v.values
    eigenvectors = v.vectors
    max_eigenvalue = maximum(abs.(eigenvalues))
    max_eigenvalue_index = argmax(abs.(eigenvalues))
    max_eigenvector = eigenvectors[:, max_eigenvalue_index]
    return (max_eigenvalue, max_eigenvector)
end

# Eigenvalues
λ11 = eigmax(G1)
λ22 = eigmax(G2)
λ33 = eigmax(G3)

λ12 = eigmax(W12p) * eigmax(W21p)
λ21 = λ12#eigmax(W21p) * eigmax(W12p)
λ13 = eigmax(W13p) * eigmax(W31p)
λ31 = λ13
λ23 = eigmax(W23p) * eigmax(W32p)
λ32 = λ23

println("λ₁₁: ", λ11)
println("λ₂₂: ", λ22)
println("λ₃₃: ", λ33)
println("λ₁₂: ", λ12)
println("λ₁₃: ", λ13)
println("λ₂₃: ", λ23)

λ₁₁: 3.4203762111170852
λ₂₂: 4.694988076660709
λ₃₃: 2.7092753594369223
λ₁₂: 1.0
λ₁₃: 0.0
λ₂₃: 1.0


$$\hat a_v= x_1u_1+\dots+x_ru_r$$
$$\{u_i\}\in\mathbb R^{m_v}$$
$$m_v = |G_p|$$

$$\hat{\mathbf{C}}\ \mathbf y = (0,\dots,0,1)^T$$
$$\mathbf{y}:=(x_1,\ \dots\ ,\ x_r,\ K)$$
$$\hat{\mathbf C}=\left(\frac{C}{1^{T}}\frac{-1}{0}\right)$$
$$C=(c_{st})_{s,t} \quad\text{ is }\quad r\times r$$

$$c_{st}:=\sum_{p=1}^n\langle W^\prime_{vp} u_s- \lambda^\prime_{vp} u_s,\ W^\prime_{vp} u_t- \lambda^\prime_{vp} u_t\rangle$$

A solution that is not restricted to a particular subspace is obtained when $r = m_v$ and $u_1,\dots, u_{m_v}$ is the canonical basis of $\mathbb R^{m_v}$. This solution is the one with the smallest error.

## Reduction Vectors

In [14]:
# canonical basis
canonical_basis = Diagonal(ones(13))

e1 = canonical_basis[:,1]
e2 = canonical_basis[:,2]
e3 = canonical_basis[:,3]
e4 = canonical_basis[:,4]
e5 = canonical_basis[:,5]
e6 = canonical_basis[:,6]
e7 = canonical_basis[:,7]
e8 = canonical_basis[:,8]
e9 = canonical_basis[:,9]
e10 = canonical_basis[:,10]
e11 = canonical_basis[:,11]
e12 = canonical_basis[:,12]
e13 = canonical_basis[:,13]

u1 = [e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 e12 e13]

canonical_basis = Diagonal(ones(12))

e1 = canonical_basis[:,1]
e2 = canonical_basis[:,2]
e3 = canonical_basis[:,3]
e4 = canonical_basis[:,4]
e5 = canonical_basis[:,5]
e6 = canonical_basis[:,6]
e7 = canonical_basis[:,7]
e8 = canonical_basis[:,8]
e9 = canonical_basis[:,9]
e10 = canonical_basis[:,10]
e11 = canonical_basis[:,11]
e12 = canonical_basis[:,12]

u2 = [e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 e12]


canonical_basis = Diagonal(ones(6))

e1 = canonical_basis[:,1]
e2 = canonical_basis[:,2]
e3 = canonical_basis[:,3]
e4 = canonical_basis[:,4]
e5 = canonical_basis[:,5]
e6 = canonical_basis[:,6]


u3 = [e1 e2 e3 e4 e5 e6]

6×6 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0

$$\hat C = \begin{pmatrix} C & \mathbf{1} \\ \mathbf{1}^T & 0 \end{pmatrix}$$

$$\mathbf{\hat{C} y} =(0,\dots,0, 1)$$
$$\mathbf y =(x_1,\dots,x_r, K)$$

In [15]:
# CLUSTER 1
# v = 1
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t
r1 = g1_dim[1]
C1 = zeros(r1, r1)  # Initialize the matrix C

for i in 1:r1
    for j in 1:r1
        term1 = dot(W11p * u1[:, i] - λ11 * u1[:, i], W11p * u1[:, j] - λ11 * u1[:, j])
        term2 = dot(W12p * u1[:, i] - λ12 * u1[:, i], W12p * u1[:, j] - λ12 * u1[:, j])
        term3 = dot(W13p * u1[:, i] - λ13 * u1[:, i], W13p * u1[:, j] - λ13 * u1[:, j])
        C1[i, j] = term1 + term2 + term3
    end
end

ones_col = ones(size(C1, 1))  
ones_row = ones(1, size(C1, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C1, ones_col)  
C1_hat = vcat(top_row, ones_row)  

C1_hat

14×14 Matrix{Float64}:
 16.699    -6.84075  -6.84075  -6.84075  …   0.0       0.0       0.0      1.0
 -6.84075  14.699     1.0       1.0          0.0       0.0       1.0      1.0
 -6.84075   1.0      14.699     1.0          1.0       1.0       1.0      1.0
 -6.84075   1.0       1.0      14.699        1.0       1.0       1.0      1.0
 -6.84075   1.0       1.0       1.0          0.0       1.0       1.0      1.0
  1.0      -6.84075   0.0       0.0      …   0.0       0.0      -6.84075  1.0
  1.0       0.0      -6.84075   0.0         -6.84075  -6.84075  -6.84075  1.0
  1.0       0.0       0.0      -6.84075     -6.84075  -6.84075  -6.84075  1.0
  1.0       0.0       0.0       0.0          0.0      -6.84075  -6.84075  1.0
  0.0       1.0       1.0       1.0          2.0       2.0       3.0      1.0
  0.0       0.0       1.0       1.0      …  13.699     2.0       2.0      1.0
  0.0       0.0       1.0       1.0          2.0      14.699     3.0      1.0
  0.0       1.0       1.0       1.0      

In [16]:
rhs = zeros(size(C1_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C1_hat \ rhs

coefficients = y[1:r1]  

a1 = u1 * coefficients

13-element Vector{Float64}:
 0.03671660968145352
 0.030152989162889714
 0.04588827469461988
 0.04588827469461992
 0.02579935605039592
 0.07619576963732412
 0.133959230709688
 0.13395923070968804
 0.06678655972904103
 0.10352631181188926
 0.08078773725113474
 0.09880054065325064
 0.12153911521400514

In [17]:
# CLUSTER 2
# v = 2
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t
r2 = g2_dim[1]
C2 = zeros(r2, r2)  # Initialize the matrix C

for i in 1:r2
    for j in 1:r2
        term1 = dot(W21p * u2[:, i] - λ21 * u2[:, i], W21p * u2[:, j] - λ21 * u2[:, j])
        term2 = dot(W22p * u2[:, i] - λ22 * u2[:, i], W22p * u2[:, j] - λ22 * u2[:, j])
        term3 = dot(W23p * u2[:, i] - λ23 * u2[:, i], W23p * u2[:, j] - λ23 * u2[:, j])
        C2[i, j] = term1 + term2 + term3
    end
end
ones_col = ones(size(C2, 1))  
ones_row = ones(1, size(C2, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C2, ones_col)  
C2_hat = vcat(top_row, ones_row)  

C2_hat

13×13 Matrix{Float64}:
 25.0429    0.0       0.0       0.0      …   0.0       1.0       0.0      1.0
  0.0      28.0429    3.0       4.0          4.0      -9.38998  -9.38998  1.0
  0.0       3.0      26.0429    3.0          2.0      -9.38998   0.0      1.0
  0.0       4.0       3.0      27.0429       3.0      -9.38998  -9.38998  1.0
  0.0       5.0       3.0       4.0          4.0      -9.38998  -9.38998  1.0
  1.0      -9.38998   0.0       0.0      …  -9.38998   3.0       3.0      1.0
  1.0      -9.38998  -9.38998  -9.38998     -9.38998   5.0       4.0      1.0
  1.0      -9.38998  -9.38998  -9.38998     -9.38998   5.0       4.0      1.0
 -9.38998   4.0       3.0       3.0          3.0      -9.38998   0.0      1.0
  0.0       4.0       2.0       3.0         28.0429    0.0      -9.38998  1.0
  1.0      -9.38998  -9.38998  -9.38998  …   0.0      28.0429    3.0      1.0
  0.0      -9.38998   0.0      -9.38998     -9.38998   3.0      27.0429   1.0
  1.0       1.0       1.0       1.0      

In [18]:
rhs = zeros(size(C2_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C2_hat \ rhs

coefficients = y[1:r2]  

a2 = u2 * coefficients

12-element Vector{Float64}:
 0.02035349511022526
 0.09977868897224149
 0.06783438480777043
 0.08393947034618121
 0.09977868897224149
 0.07735859273308107
 0.10881686468603428
 0.10881686468603428
 0.08462283912442876
 0.07723338652758573
 0.09352847281481348
 0.0779382512193626

In [19]:
# CLUSTER 3
# v = 3
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t

r3 = g3_dim[1]
C3 = zeros(r3, r3) 

for i in 1:r3
    for j in 1:r3
        term1 = dot(W31p * u3[:, i] - λ31 * u3[:, i], W31p * u3[:, j] - λ31 * u3[:, j])
        term2 = dot(W32p * u3[:, i] - λ32 * u3[:, i], W32p * u3[:, j] - λ32 * u3[:, j])
        term3 = dot(W33p * u3[:, i] - λ33 * u3[:, i], W33p * u3[:, j] - λ33 * u3[:, j])
        C3[i, j] = term1 + term2 + term3
    end
end

ones_col = ones(size(C3, 1))  
ones_row = ones(1, size(C3, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C3, ones_col)  
C3_hat = vcat(top_row, ones_row)  

C3_hat

7×7 Matrix{Float64}:
  9.34017  -4.41855   1.0       1.0      -4.41855   1.0      1.0
 -4.41855  10.3402    1.0       1.0      -4.41855   1.0      1.0
  1.0       1.0       9.34017  -4.41855  -4.41855   1.0      1.0
  1.0       1.0      -4.41855  10.3402   -4.41855   1.0      1.0
 -4.41855  -4.41855  -4.41855  -4.41855  13.3402   -5.41855  1.0
  1.0       1.0       1.0       1.0      -5.41855   9.34017  1.0
  1.0       1.0       1.0       1.0       1.0       1.0      0.0

In [20]:
rhs = zeros(size(C3_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C3_hat \ rhs

coefficients = y[1:r3]  

a3 = u3 * coefficients

6-element Vector{Float64}:
 0.16603628392086836
 0.15478624039512281
 0.1660362839208683
 0.1547862403951228
 0.26152492610732053
 0.09683002526069712

# Compute $\mu_{vp}$ for every $p$

$$\mu_{vp}=\frac{a_v^T K_{vp}a_v}{||a_v||^2}$$

In [ ]:
μ11 =