In [1]:
using MAT
using DataStructures
using LinearAlgebra

# Step 1: Identification of modules

First, we load the precomputed matrices from MATLAB.

In [6]:
adjacency_file = matopen("./matrices/adjacency-reduced-weighted_2.mat")
cluster1_file = matopen("./matrices/S1-weighted_2.mat")
cluster2_file = matopen("./matrices/S2-weighted_2.mat")
cluster3_file = matopen("./matrices/S3-weighted_2.mat")

S = read(adjacency_file, "S")
println(issymmetric(S))

G1 = read(cluster1_file, "S1")
G2 = read(cluster2_file, "S2")
G3 = read(cluster3_file, "S3")

s_dim = size(S)
g1_dim = size(G1)
g2_dim = size(G2)
g3_dim = size(G3)

println("Matrix dimensions:")
println("\t[S] Adjacency matrix: ", s_dim)
println("\t[G1] Cluster 1: ", g1_dim)
println("\t[G2] Cluster 2: ", g2_dim)
println("\t[G3] Cluster 3: ", g3_dim)

true
Matrix dimensions:
	[S] Adjacency matrix: (31, 31)
	[G1] Cluster 1: (13, 13)
	[G2] Cluster 2: (12, 12)
	[G3] Cluster 3: (6, 6)


In [7]:
G1

13×13 Matrix{Float64}:
     0.0   10000.0  10000.0  1317.76  …      0.0      0.0      0.0      0.0
 10000.0       0.0      0.0     0.0          0.0      0.0      0.0      0.0
 10000.0       0.0      0.0     0.0          0.0      0.0      0.0      0.0
  1317.76      0.0      0.0     0.0          0.0      0.0      0.0      0.0
  1317.76      0.0      0.0     0.0          0.0      0.0      0.0      0.0
     0.0      60.0      0.0     0.0   …  10000.0      0.0      0.0  10000.0
     0.0       0.0     60.0     0.0      10000.0  10000.0  10000.0  10000.0
     0.0       0.0      0.0    60.0      10000.0  10000.0  10000.0  10000.0
     0.0       0.0      0.0     0.0          0.0      0.0  10000.0  10000.0
     0.0       0.0      0.0     0.0          0.0      0.0      0.0      0.0
     0.0       0.0      0.0     0.0   …      0.0      0.0      0.0      0.0
     0.0       0.0      0.0     0.0          0.0      0.0      0.0      0.0
     0.0       0.0      0.0     0.0          0.0      0.0      0.

In [8]:
G2

12×12 Matrix{Float64}:
  0.0      0.0         0.0     …    10.0     0.0    0.0       0.0
  0.0      0.0         0.0           0.0     0.0   70.0001   70.0001
  0.0      0.0         0.0           0.0     0.0   70.0001    0.0
  0.0      0.0         0.0           0.0     0.0   70.0001   70.0001
  0.0      0.0         0.0           0.0     0.0   70.0001   70.0001
  0.0  10000.0         0.0     …  1000.0  1000.0    0.0       0.0
  0.0  10000.0     10000.0        1000.0  1000.0    0.0       0.0
  0.0  10000.0     10000.0        1000.0  1000.0    0.0       0.0
 10.0      0.0         0.0           0.0     0.0  180.0       0.0
  0.0      0.0         0.0           0.0     0.0    0.0     180.0
  0.0     70.0001     70.0001  …   180.0     0.0    0.0       0.0
  0.0     70.0001      0.0           0.0   180.0    0.0       0.0

In [9]:
G3

6×6 Matrix{Float64}:
  0.0     70.0001   0.0      0.0     70.0117  0.0
 70.0001   0.0      0.0      0.0     70.0001  0.0
  0.0      0.0      0.0     70.0001  70.0001  0.0
  0.0      0.0     70.0001   0.0     70.0001  0.0
 70.0117  70.0001  70.0001  70.0001   0.0     0.014
  0.0      0.0      0.0      0.0      0.014   0.0

## Adjacency submatrices

$W_{vp}$ is the submatrix of size $m_v \times m_p$ consisting of all interactions from $G_p$ and $G_v$.

($m_i$ is the size of the cluster $i$)

$$W_{12}$$

In [10]:
row_start = g1_dim[1]+1
row_end = g1_dim[1] + g2_dim[1]
col_start = 1
col_end = g1_dim[2]
W12 = S[row_start:row_end, col_start:col_end]

12×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1
 0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{21}$$

In [11]:
row_start = 1
row_end = g1_dim[1]
col_start = g1_dim[2] + 1                            # Same column range as W12
col_end = col_start -1 + g2_dim[2]
W21 = S[row_start:row_end, col_start:col_end]

13×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [12]:
W12 == W21' # The matrix is symmetric, thus we only need the transpose.

true

$$W_{13}$$

In [13]:
row_start = g1_dim[1] + g2_dim[1] +1
row_end = g1_dim[1] + g2_dim[1] + g3_dim[1]
col_start = 1
col_end = g1_dim[2]
W13 = S[row_start:row_end, col_start:col_end]

6×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{31}$$

In [14]:
W31 = Matrix(W13')
W31

13×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

$$W_{23}$$

In [15]:
row_start = g1_dim[1] + g2_dim[1] +1
row_end = g1_dim[1] + g2_dim[1] + g3_dim[1]
col_start = g1_dim[2]+1
col_end = g1_dim[2] + g2_dim[2]
W23  = S[row_start:row_end, col_start:col_end]

6×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  70.0001   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0     70.0001
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0

$$W_{32}$$

In [16]:
W32 = Matrix(W23')
W32

12×6 Matrix{Float64}:
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
 70.0001  0.0   0.0     0.0  0.0  0.0
  0.0     0.0  70.0001  0.0  0.0  0.0

## Diagonal in-degree submatrices 

$K_{vp}$ is the in-degree matrix of size $m_v \times m_v$ from $G_p$ to $G_v$.

$$K_{vp} = \text{diag}(k_{i_1}^p,\dots, k_{i_{m_v}}^p)$$
$k_i^p = \sum_{j\in G_p} w_{ij}$

$$K_{vp}$$

$$K_{11} = \sum_j w_{1j}$$

In [17]:
function compute_in_degree(W::Matrix)
    # Initialize an empty vector to store the sums of each column
    sums = zeros(size(W, 2))
    
    # Iterate over each column of W and calculate the sum
    for i in 1:size(W, 2)
        sums[i] = sum(W[:, i])
    end
    
    # Construct the diagonal matrix K using the computed sums
    K = Diagonal(sums)
    
    return K
end

compute_in_degree (generic function with 1 method)

In [18]:
K11 = compute_in_degree(G1)
K22 = compute_in_degree(G2)
K33 = compute_in_degree(G3);

In [19]:
K11

13×13 Diagonal{Float64, Vector{Float64}}:
 22635.5       ⋅        ⋅       ⋅    …       ⋅        ⋅        ⋅        ⋅ 
      ⋅   10060.0       ⋅       ⋅            ⋅        ⋅        ⋅        ⋅ 
      ⋅        ⋅   10060.0      ⋅            ⋅        ⋅        ⋅        ⋅ 
      ⋅        ⋅        ⋅   1377.76          ⋅        ⋅        ⋅        ⋅ 
      ⋅        ⋅        ⋅       ⋅            ⋅        ⋅        ⋅        ⋅ 
      ⋅        ⋅        ⋅       ⋅    …       ⋅        ⋅        ⋅        ⋅ 
      ⋅        ⋅        ⋅       ⋅            ⋅        ⋅        ⋅        ⋅ 
      ⋅        ⋅        ⋅       ⋅            ⋅        ⋅        ⋅        ⋅ 
      ⋅        ⋅        ⋅       ⋅            ⋅        ⋅        ⋅        ⋅ 
      ⋅        ⋅        ⋅       ⋅       30000.0       ⋅        ⋅        ⋅ 
      ⋅        ⋅        ⋅       ⋅    …       ⋅   20000.0       ⋅        ⋅ 
      ⋅        ⋅        ⋅       ⋅            ⋅        ⋅   30000.0       ⋅ 
      ⋅        ⋅        ⋅       ⋅            ⋅        ⋅   

In [20]:
K22

12×12 Diagonal{Float64, Vector{Float64}}:
 10.0       ⋅        ⋅        ⋅        ⋅   …      ⋅       ⋅      ⋅      ⋅ 
   ⋅   30140.0       ⋅        ⋅        ⋅          ⋅       ⋅      ⋅      ⋅ 
   ⋅        ⋅   20070.0       ⋅        ⋅          ⋅       ⋅      ⋅      ⋅ 
   ⋅        ⋅        ⋅   20140.0       ⋅          ⋅       ⋅      ⋅      ⋅ 
   ⋅        ⋅        ⋅        ⋅   30140.0         ⋅       ⋅      ⋅      ⋅ 
   ⋅        ⋅        ⋅        ⋅        ⋅   …      ⋅       ⋅      ⋅      ⋅ 
   ⋅        ⋅        ⋅        ⋅        ⋅          ⋅       ⋅      ⋅      ⋅ 
   ⋅        ⋅        ⋅        ⋅        ⋅          ⋅       ⋅      ⋅      ⋅ 
   ⋅        ⋅        ⋅        ⋅        ⋅      3190.0      ⋅      ⋅      ⋅ 
   ⋅        ⋅        ⋅        ⋅        ⋅          ⋅   3180.0     ⋅      ⋅ 
   ⋅        ⋅        ⋅        ⋅        ⋅   …      ⋅       ⋅   460.0     ⋅ 
   ⋅        ⋅        ⋅        ⋅        ⋅          ⋅       ⋅      ⋅   390.0

In [21]:
K33

6×6 Diagonal{Float64, Vector{Float64}}:
 140.012     ⋅      ⋅      ⋅      ⋅      ⋅ 
    ⋅     140.0     ⋅      ⋅      ⋅      ⋅ 
    ⋅        ⋅   140.0     ⋅      ⋅      ⋅ 
    ⋅        ⋅      ⋅   140.0     ⋅      ⋅ 
    ⋅        ⋅      ⋅      ⋅   280.026   ⋅ 
    ⋅        ⋅      ⋅      ⋅      ⋅     0.014

In [22]:
K12 = compute_in_degree(W12)
K13 = compute_in_degree(W13)
K23 = compute_in_degree(W23);

In [23]:
K21 = compute_in_degree(W21)
K31 = compute_in_degree(W31)
K32 = compute_in_degree(W32);

In [24]:
K21 == K12

false

# Step 2: Construction of observables 

$$W_{vp}^\prime \hat a_v= \lambda_{vp}^\prime\hat a_p$$
we focus on fixed $v$, variable $p$.

$$W^\prime_{vp} = W^T_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad W^\prime_{vp} = W^T_{pv}W^T_{vp}\quad \text{ if }\quad v\ne p$$
$$\lambda^\prime_{vp} = \lambda_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad \lambda^\prime_{vp} = \lambda_{pv}\lambda_{vp}\quad \text{ if }\quad v\ne p$$

In [25]:
W11p = G1'
W12p = W12' * W21'
W21p = W21' * W12'
W13p = W13' * W31'
W31p = W31' * W13'
W22p = G2'
W23p = W23' * W32'
W32p = W32' * W23'
W33p= G3'

println(size(W11p))
println(size(W22p))
println(size(W33p))
println(size(W12p))
println(size(W21p))
println(size(W13p))
println(size(W31p))
println(size(W23p))
println(size(W32p))

(13, 13)
(12, 12)
(6, 6)
(13, 13)
(12, 12)
(13, 13)
(6, 6)
(12, 12)
(6, 6)


In [26]:
# Eigenvalues
λ11 = eigmax(G1)
λ22 = eigmax(G2)
λ33 = eigmax(G3)

λ12 = eigmax(W12p) * eigmax(W21p)
λ21 = λ12
λ13 = eigmax(W13p) * eigmax(W31p)
λ31 = λ13
λ23 = eigmax(W23p) * eigmax(W32p)
λ32 = λ23

println("λ₁₁: ", λ11)
println("λ₂₂: ", λ22)
println("λ₃₃: ", λ33)
println("λ₁₂: ", λ12)
println("λ₁₃: ", λ13)
println("λ₂₃: ", λ23)

λ₁₁: 31964.09199932105
λ₂₂: 30298.791157659798
λ₃₃: 179.31450299794622
λ₁₂: 0.00010000173124573948
λ₁₃: 0.0
λ₂₃: 2.401009604024009e7


$$\hat a_v= x_1u_1+\dots+x_ru_r$$
$$\{u_i\}\in\mathbb R^{m_v}$$
$$m_v = |G_p|$$

$$\hat{\mathbf{C}}\ \mathbf y = (0,\dots,0,1)^T$$
$$\mathbf{y}:=(x_1,\ \dots\ ,\ x_r,\ K)$$
$$\hat{\mathbf C}=\left(\frac{C}{1^{T}}\frac{-1}{0}\right)$$
$$C=(c_{st})_{s,t} \quad\text{ is }\quad r\times r$$

$$c_{st}:=\sum_{p=1}^n\langle W^\prime_{vp} u_s- \lambda^\prime_{vp} u_s,\ W^\prime_{vp} u_t- \lambda^\prime_{vp} u_t\rangle$$

A solution that is not restricted to a particular subspace is obtained when $r = m_v$ and $u_1,\dots, u_{m_v}$ is the canonical basis of $\mathbb R^{m_v}$. This solution is the one with the smallest error.

## Reduction Vectors

In [27]:
function get_standard_basis_vectors(dimension)
    canonical_basis = Diagonal(ones(dimension))
    return canonical_basis[:, 1:dimension]
end

u1 = get_standard_basis_vectors(13)
u2 = get_standard_basis_vectors(12)
u3 = get_standard_basis_vectors(6)

6×6 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0

$$\hat C = \begin{pmatrix} C & \mathbf{1} \\ \mathbf{1}^T & 0 \end{pmatrix}$$

$$\mathbf{\hat{C} y} =(0,\dots,0, 1)$$
$$\mathbf y =(x_1,\dots,x_r, K)$$

In [28]:
# CLUSTER 1
# v = 1
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t
r1 = g1_dim[1]
C1 = zeros(r1, r1)  # Initialize the matrix C

for i in 1:r1
    for j in 1:r1
        term1 = dot(W11p * u1[:, i] - λ11 * u1[:, i], W11p * u1[:, j] - λ11 * u1[:, j])
        term2 = dot(W12p * u1[:, i] - λ12 * u1[:, i], W12p * u1[:, j] - λ12 * u1[:, j])
        term3 = dot(W13p * u1[:, i] - λ13 * u1[:, i], W13p * u1[:, j] - λ13 * u1[:, j])
        C1[i, j] = term1 + term2 + term3
    end
end

ones_col = ones(size(C1, 1))  
ones_row = ones(1, size(C1, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C1, ones_col)  
C1_hat = vcat(top_row, ones_row)  

C1_hat

14×14 Matrix{Float64}:
      1.22518e9      -6.39282e8  …       0.0             0.0        1.0
     -6.39282e8       1.12171e9          0.0        600000.0        1.0
     -6.39282e8       1.0e8         600000.0        600000.0        1.0
     -8.42418e7       1.31776e7     600000.0        600000.0        1.0
     -8.42418e7       1.31776e7     600000.0        600000.0        1.0
 600000.0            -3.83569e6  …       0.0            -6.39282e8  1.0
 600000.0             0.0               -6.39282e8      -6.39282e8  1.0
  79065.4             0.0               -6.39282e8      -6.39282e8  1.0
  79065.4             0.0               -6.39282e8      -6.39282e8  1.0
      0.0        600000.0                2.0e8           3.0e8      1.0
      0.0             0.0        …       2.0e8           2.0e8      1.0
      0.0             0.0                1.3217e9        3.0e8      1.0
      0.0        600000.0                3.0e8           1.4217e9   1.0
      1.0             1.0                

In [29]:
rhs = zeros(size(C1_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C1_hat \ rhs

coefficients = y[1:r1]  

a1 = u1 * coefficients

print(a1)
sum(a1)

[0.00020432688525491804, 0.00022872576368539378, 0.0003612670793500542, 0.00030576661594318796, 0.00017322527906151727, 0.08779570833125637, 0.1584050884582004, 0.1584049842779282, 0.08779559284793376, 0.12658134667988497, 0.09911436644058527, 0.12658131055080818, 0.1540482907901078]

0.9999999999999998

In [30]:
# CLUSTER 2
# v = 2
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t
r2 = g2_dim[1]
C2 = zeros(r2, r2)  # Initialize the matrix C

for i in 1:r2
    for j in 1:r2
        term1 = dot(W21p * u2[:, i] - λ21 * u2[:, i], W21p * u2[:, j] - λ21 * u2[:, j])
        term2 = dot(W22p * u2[:, i] - λ22 * u2[:, i], W22p * u2[:, j] - λ22 * u2[:, j])
        term3 = dot(W23p * u2[:, i] - λ23 * u2[:, i], W23p * u2[:, j] - λ23 * u2[:, j])
        C2[i, j] = term1 + term2 + term3
    end
end
ones_col = ones(size(C2, 1))  
ones_row = ones(1, size(C2, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C2, ones_col)  
C2_hat = vcat(top_row, ones_row)  

C2_hat

13×13 Matrix{Float64}:
     5.76486e14   0.0         …   1800.0            0.0        1.0
     0.0          5.76486e14        -4.24184e6     -4.24184e6  1.0
     0.0          2.00005e8         -4.24184e6      0.0        1.0
     0.0          2.0001e8          -4.24184e6     -4.24184e6  1.0
     0.0          3.0001e8          -4.24184e6     -4.24184e6  1.0
 10000.0         -6.05976e8   …      1.58e6         1.58e6     1.0
 10000.0         -6.05976e8          2.98e6         2.28e6     1.0
 10000.0         -6.05976e8          2.98e6         2.28e6     1.0
    -6.05976e5    3.00126e7         -1.09076e7      0.0        1.0
     0.0          3.00126e7          0.0           -1.09076e7  1.0
  1800.0         -4.24184e6   …      5.7625e14  14700.0        1.0
     0.0         -4.24184e6      14700.0            5.7625e14  1.0
     1.0          1.0                1.0            1.0        0.0

In [31]:
rhs = zeros(size(C2_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C2_hat \ rhs

coefficients = y[1:r2]  

a2 = u2 * coefficients
print(a2)
sum(a2)

[0.08332758735576769, 0.08332769804530653, 0.08332764164527712, 0.08332764225471359, 0.08332769804530647, 0.08332769191921004, 0.08332780897831127, 0.08332780897831125, 0.08332759988109911, 0.08332759979534458, 0.0833616117556605, 0.08336161134569181]

1.0

In [32]:
# CLUSTER 3
# v = 3
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t

r3 = g3_dim[1]
C3 = zeros(r3, r3) 

for i in 1:r3
    for j in 1:r3
        term1 = dot(W31p * u3[:, i] - λ31 * u3[:, i], W31p * u3[:, j] - λ31 * u3[:, j])
        term2 = dot(W32p * u3[:, i] - λ32 * u3[:, i], W32p * u3[:, j] - λ32 * u3[:, j])
        term3 = dot(W33p * u3[:, i] - λ33 * u3[:, i], W33p * u3[:, j] - λ33 * u3[:, j])
        C3[i, j] = term1 + term2 + term3
    end
end

ones_col = ones(size(C3, 1))  
ones_row = ones(1, size(C3, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C3, ones_col)  
C3_hat = vcat(top_row, ones_row)  

C3_hat

7×7 Matrix{Float64}:
      5.76249e14  -20203.2         …  -20208.2          0.980163    1.0
 -20203.2              5.76485e14     -20203.2          0.980001    1.0
   4900.82          4900.01           -20204.0          0.980001    1.0
   4900.82          4900.01           -20204.0          0.980001    1.0
 -20208.2         -20203.2                 5.76485e14  -5.02081     1.0
      0.980163         0.980001    …      -5.02081      5.76485e14  1.0
      1.0              1.0                 1.0          1.0         0.0

In [33]:
rhs = zeros(size(C3_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C3_hat \ rhs

coefficients = y[1:r3]  

a3 = u3 * coefficients

print(a3)
sum(a3)

[0.1667120257625811, 0.16664398711729178, 0.1667120257625808, 0.16664398711729203, 0.16664398712897818, 0.16664398711127607]

0.9999999999999999

## Compute $\mu_{vp}$ for every $p$

$$\mu_{vp}=\frac{a_v^T K_{vp}a_v}{||a_v||^2}$$

In [34]:
mu11 = dot(a1, K11 * a1) / dot(a1, a1)
mu22 = dot(a2, K22 * a2) / dot(a2, a2)
mu33 = dot(a3, K33 * a3) / dot(a3, a3)

println("μ₁₁: ", mu11)
println("μ₂₂: ", mu22)
println("μ₃₃: ", mu33)

μ₁₁: 33739.92780559562
μ₂₂: 17807.661268159165
μ₃₃: 140.00867213154856


In [35]:
mu12 = dot(a1, K12 * a1) / dot(a1, a1)
mu13 = dot(a1, K13 * a1) / dot(a1, a1)
mu23 = dot(a2, K23 * a2) / dot(a2, a2)

println("μ₁₂: ", mu12)
println("μ₁₃: ", mu13)
println("μ₂₃: ", mu23)

μ₁₂: 0.09412478241505923
μ₁₃: 0.0
μ₂₃: 11.674597316669209


In [36]:
mu21 = dot(a2, K21 * a2) / dot(a2, a2)
mu31 = dot(a3, K31 * a3) / dot(a3, a3)
mu32 = dot(a3, K32 * a3) / dot(a3, a3)

println("μ₂₁: ", mu21)
println("μ₃₁: ", mu31)
println("μ₃₂: ", mu32)

μ₂₁: 0.058325499624567366
μ₃₁: 0.0
μ₃₂: 23.34605808990502


In [37]:
mu_mat = [mu11 mu12 mu13; mu21 mu22 mu23; mu31 mu32 mu33]

3×3 Matrix{Float64}:
 33739.9            0.0941248    0.0
     0.0583255  17807.7         11.6746
     0.0           23.3461     140.009