In [62]:
using MAT
using DataStructures
using LinearAlgebra

# Matrices

We load the precomputed matrices from MATLAB.

In [63]:
adjacency_file = matopen("./matrices/adjacency-reduced.mat")
cluster1_file = matopen("./matrices/S1-reduced.mat")
cluster2_file = matopen("./matrices/S2-reduced.mat")
cluster3_file = matopen("./matrices/S3-reduced.mat")

MAT.MAT_v5.Matlabv5File(IOStream(<file ./matrices/S3-reduced.mat>), false, #undef)

In [94]:
S = read(adjacency_file, "S")
G1 = read(cluster1_file, "S1")
G2 = read(cluster2_file, "S2")
G3 = read(cluster3_file, "S3")

s_dim = size(S)
g1_dim = size(G1)
g2_dim = size(G2)
g3_dim = size(G3)

println("Matrix dimensions:")
println("\t[S] Adjacency matrix: ", s_dim)
println("\t[G1] Cluster 1: ", s1_dim)
println("\t[G2] Cluster 2: ", s2_dim)
println("\t[G3] Cluster 3: ", s3_dim)

Matrix dimensions:
	[S] Adjacency matrix: (31, 31)
	[G1] Cluster 1: (13, 13)
	[G2] Cluster 2: (12, 12)
	[G3] Cluster 3: (6, 6)


## Adjacency Submatrices $W_{vp}$

$W_{vp}$ is the adjacency matrix consisting of all interactions between $G_p$ and $G_v$

$$W_{12}$$

In [65]:
row_start = s1_dim[1]+1
row_end = s1_dim[1] + s2_dim[1]
col_start = 1
col_end = s1_dim[2]
W12 = S[row_start:row_end, col_start:col_end]

12×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{13}$$

In [66]:
row_start = s1_dim[1] + s2_dim[1] +1
row_end = s1_dim[1] + s2_dim[1] + s3_dim[1]
col_start = 1
col_end = s1_dim[2]
W13 = S[row_start:row_end, col_start:col_end]

6×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{23}$$

In [67]:
row_start = s1_dim[1] + s2_dim[1] +1
row_end = s1_dim[1] + s2_dim[1] + s3_dim[1]
col_start = s1_dim[2]+1
col_end = s1_dim[2] + s2_dim[2]
W23  = S[row_start:row_end, col_start:col_end]

6×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

## Diagonal In-Degree Submatrices $K_{vp}$

$K_{vp}$ is the in-degree submatrix from $G_v$ to $G_p$.


> In our case we just need K?
>
> What shape would $K_{12}$ have? wouldn't it just be the number of connections, i.e. 7

In [97]:
K = [[sum(W12 .== 1),0,0] [0,sum(W13 .== 1),0] [0,0,sum(W23 .== 1)]]

3×3 Matrix{Int64}:
 7  0  0
 0  0  0
 0  0  2

(Now Same Clusters)

In [98]:
K2 = [[sum(S1 .==1), 0, 0] [0, sum(S2 .==1), 0] [0, 0, sum(S3 .==1)]]

3×3 Matrix{Int64}:
 40   0   0
  0  52   0
  0   0  14

## Compatibility Equations

$$W_{vp}^\prime \hat a_v= \lambda_{vp}^\prime\hat a_p$$
fixed $v$, variable $p$.

$$W^\prime_{vp} = W^T_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad W^\prime_{vp} = W^T_{pv}W^T_{vp}\quad \text{ if }\quad v\ne p$$
$$\lambda^\prime_{vp} = \lambda_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad \lambda^\prime_{vp} = \lambda_{pv}\lambda_{vp}\quad \text{ if }\quad v\ne p$$

In [72]:
# Matrices
W₁₁ = S1'
W₂₂ = S2'
W₃₃ = S3'

W₁₂ = W12 * W12' # we have to transpose only one? otherwise we cannot compute the product.
W₁₃ = W13 * W13'
W₂₃ = W23 * W23'

6×6 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [73]:
# Eigenvalues
λ₁₁ = eigmax(W₁₁)
λ₂₂ = eigmax(W₂₂)
λ₃₃ = eigmax(W₃₃)

λ₁₂ = eigmax(W₁₂) * eigmax(W₁₂)
λ₁₃ = eigmax(W₁₃) * eigmax(W₁₃)
λ₂₃ = eigmax(W₂₃) * eigmax(W₂₃)

println("λ₁₁: ", λ₁₁)
println("λ₂₂: ", λ₂₂)
println("λ₃₃: ", λ₃₃)
println("λ₁₂: ", λ₁₂)
println("λ₁₃: ", λ₁₃)
println("λ₂₃: ", λ₂₃)

λ₁₁: 3.4203762111170852
λ₂₂: 4.694988076660709
λ₃₃: 2.7092753594369223
λ₁₂: 1.0
λ₁₃: 0.0
λ₂₃: 1.0


$$\hat a_v= x_1u_1+\dots+x_ru_r$$
$$\{u_i\}\in\mathbb R^{m_v}$$
$$m_v = |G_p|$$

$$\hat{\mathbf{C}}\ \mathbf y = (0,\dots,0,1)^T$$
$$\mathbf{y}:=(x_1,\ \dots\ ,\ x_r,\ K)$$
$$\hat{\mathbf C}=\left(\frac{C}{1^{T}}\frac{-1}{0}\right)$$
$$C=(c_{st})_{s,t} \quad\text{ is }\quad r\times r$$

$$c_{st}:=\sum_{p=1}^n\langle W^\prime_{vp} u_s- \lambda^\prime_{vp} u_s,\ W^\prime_{vp} u_t- \lambda^\prime_{vp} u_t\rangle$$

A solution that is not restricted to a particular subspace is obtained when $r = m_v$ and $u_1,\dots, u_{m_v}$ is the canonical basis of $\mathbb R^{m_v}$. This solution is the one with the smallest error.

In [86]:
# CLUSTER 1

# canonical basis
canonical_basis = Diagonal(ones(13))

e1 = canonical_basis[:,1]
e2 = canonical_basis[:,2]
e3 = canonical_basis[:,3]
e4 = canonical_basis[:,4]
e5 = canonical_basis[:,5]
e6 = canonical_basis[:,6]
e7 = canonical_basis[:,7]
e8 = canonical_basis[:,8]
e9 = canonical_basis[:,9]
e10 = canonical_basis[:,10]
e11 = canonical_basis[:,11]
e12 = canonical_basis[:,12]
e13 = canonical_basis[:,13]

u = [e1 e2 e3 e4 e5 e6 e7 e8 e9 e10 e11 e12 e13]

# Matrix C
çr = 13
C = zeros(r,r)

# Loop over each element of the matrix and calculate the inner product
for s in 1:r
  for t in 1:r
    C[s,t] = dot(W₁₁ * u[s] .- λ₁₁ * us[s], W₁₁ * u[t] .- λ₁₁ * us[t])
                + dot(W₁₂ * u[s] .- λ₁₂ * us[s], W₁₂ * u[t] .- λ₁₂ * us[t])
                + dot(W₁₃ * u[s] .- λ₁₃ * us[s], W₁₃ * u[t] .- λ₁₃ * us[t])
  end
end

C

13×13 Matrix{Float64}:
 1743.5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
    0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0