In [1]:
using MAT
using DataStructures
using LinearAlgebra

# Step 1: Identification of modules

First, we load the precomputed matrices from MATLAB.

In [2]:
adjacency_file = matopen("./matrices/adjacency-reduced.mat")
cluster1_file = matopen("./matrices/S1-reduced.mat")
cluster2_file = matopen("./matrices/S2-reduced.mat")
cluster3_file = matopen("./matrices/S3-reduced.mat")

S = read(adjacency_file, "S")
G1 = read(cluster1_file, "S1")
G2 = read(cluster2_file, "S2")
G3 = read(cluster3_file, "S3")

s_dim = size(S)
g1_dim = size(G1)
g2_dim = size(G2)
g3_dim = size(G3)

println("Matrix dimensions:")
println("\t[S] Adjacency matrix: ", s_dim)
println("\t[G1] Cluster 1: ", g1_dim)
println("\t[G2] Cluster 2: ", g2_dim)
println("\t[G3] Cluster 3: ", g3_dim)

Matrix dimensions:
	[S] Adjacency matrix: (31, 31)
	[G1] Cluster 1: (13, 13)
	[G2] Cluster 2: (12, 12)
	[G3] Cluster 3: (6, 6)


## Adjacency submatrices

$W_{vp}$ is the submatrix of size $m_v \times m_p$ consisting of all interactions from $G_p$ and $G_v$.

($m_i$ is the size of the cluster $i$)

$$W_{12}$$

In [3]:
row_start = g1_dim[1]+1
row_end = g1_dim[1] + g2_dim[1]
col_start = 1
col_end = g1_dim[2]
W12 = S[row_start:row_end, col_start:col_end]

12×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{21}$$

In [4]:
row_start = 1
row_end = g1_dim[1]
col_start = g1_dim[2] + 1                            # Same column range as W12
col_end = col_start -1 + g2_dim[2]
W21 = S[row_start:row_end, col_start:col_end]

13×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [5]:
W12 == W21' # The matrix is symmetric, thus we only need the transpose.

true

$$W_{13}$$

In [6]:
row_start = g1_dim[1] + g2_dim[1] +1
row_end = g1_dim[1] + g2_dim[1] + g3_dim[1]
col_start = 1
col_end = g1_dim[2]
W13 = S[row_start:row_end, col_start:col_end]

6×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{31}$$

In [7]:
W31 = W13'
W31

13×6 adjoint(::Matrix{Float64}) with eltype Float64:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

$$W_{23}$$

In [8]:
row_start = g1_dim[1] + g2_dim[1] +1
row_end = g1_dim[1] + g2_dim[1] + g3_dim[1]
col_start = g1_dim[2]+1
col_end = g1_dim[2] + g2_dim[2]
W23  = S[row_start:row_end, col_start:col_end]

6×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{32}$$

In [9]:
W32 = W23'
W32

12×6 adjoint(::Matrix{Float64}) with eltype Float64:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0

## Diagonal in-degree submatrices 

$K_{vp}$ is the in-degree matrix of size $m_v \times m_v$ from $G_p$ to $G_v$.

$$K_{vp} = \text{diag}(k_{i_1}^p,\dots, k_{i_{m_v}}^p)$$
$k_i^p = \sum_{j\in G_p} w_{ij}$

$$K_{vp}$$

$$K_{11} = \sum_j w_{1j}$$

In [37]:
function calculate_intercluster_indegree(W, target_node)
    return W[target_node, :]  # Extract the row corresponding to the target node
end

K11 = diagm(calculate_intercluster_indegree(G1, 1))  
K12 = diagm(calculate_intercluster_indegree(G1, 2))  
K13 = diagm(calculate_intercluster_indegree(G1, 3))  
K14 = diagm(calculate_intercluster_indegree(G1, 4))  
K15 = diagm(calculate_intercluster_indegree(G1, 5))  
K16 = diagm(calculate_intercluster_indegree(G1, 6))  
K17 = diagm(calculate_intercluster_indegree(G1, 7))  
K18 = diagm(calculate_intercluster_indegree(G1, 8))  
K19 = diagm(calculate_intercluster_indegree(G1, 9))  
K110 = diagm(calculate_intercluster_indegree(G1, 10))
K111 = diagm(calculate_intercluster_indegree(G1, 11))  
K112 = diagm(calculate_intercluster_indegree(G1, 12))  
K113 = diagm(calculate_intercluster_indegree(G1, 13))  


K21 = diagm(calculate_intercluster_indegree(G2, 1))  
K22 = diagm(calculate_intercluster_indegree(G2, 2))  
K23 = diagm(calculate_intercluster_indegree(G2, 3)) 
K24 = diagm(calculate_intercluster_indegree(G2, 4))
K25 = diagm(calculate_intercluster_indegree(G2, 5))
K26 = diagm(calculate_intercluster_indegree(G2, 6))
K27 = diagm(calculate_intercluster_indegree(G2, 7))
K28 = diagm(calculate_intercluster_indegree(G2, 8))
K29 = diagm(calculate_intercluster_indegree(G2, 9))
K210 = diagm(calculate_intercluster_indegree(G2, 10))
K211 = diagm(calculate_intercluster_indegree(G2, 11))
K212 = diagm(calculate_intercluster_indegree(G2, 12)) 

K31 = diagm(calculate_intercluster_indegree(G3, 1))  
K32 = diagm(calculate_intercluster_indegree(G3, 2))
K33 = diagm(calculate_intercluster_indegree(G3, 3))  
K34 = diagm(calculate_intercluster_indegree(G3, 4))
K35 = diagm(calculate_intercluster_indegree(G3, 5))
K36 = diagm(calculate_intercluster_indegree(G3, 6))

6×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

## Global in-degree submatrix

In [11]:
K = [[sum(W12 .== 1),0,0] [0,sum(W13 .== 1),0] [0,0,sum(W23 .== 1)]]

3×3 Matrix{Int64}:
 7  0  0
 0  0  0
 0  0  2

# Step 2: Construction of observables 

$$W_{vp}^\prime \hat a_v= \lambda_{vp}^\prime\hat a_p$$
we focus on fixed $v$, variable $p$.

$$W^\prime_{vp} = W^T_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad W^\prime_{vp} = W^T_{pv}W^T_{vp}\quad \text{ if }\quad v\ne p$$
$$\lambda^\prime_{vp} = \lambda_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad \lambda^\prime_{vp} = \lambda_{pv}\lambda_{vp}\quad \text{ if }\quad v\ne p$$

In [12]:
W11p = G1'
W12p = W12' * W21'
W21p = W21' * W12'
W13p = W13' * W31'
W31p = W31' * W13'
W22p = G2'
W23p = W23' * W32'
W32p = W32' * W23'
W33p= G3'

println(size(W11p))
println(size(W22p))
println(size(W33p))

(13, 13)
(12, 12)
(6, 6)


In [13]:
# Eigenvalues
λ11 = eigmax(G1)
λ22 = eigmax(G2)
λ33 = eigmax(G3)

λ12 = eigmax(W12p) * eigmax(W21p)
λ21 = λ12
λ13 = eigmax(W13p) * eigmax(W31p)
λ31 = λ13
λ23 = eigmax(W23p) * eigmax(W32p)
λ32 = λ23

println("λ₁₁: ", λ11)
println("λ₂₂: ", λ22)
println("λ₃₃: ", λ33)
println("λ₁₂: ", λ12)
println("λ₁₃: ", λ13)
println("λ₂₃: ", λ23)

λ₁₁: 3.4203762111170852
λ₂₂: 4.694988076660709
λ₃₃: 2.7092753594369223
λ₁₂: 1.0
λ₁₃: 0.0
λ₂₃: 1.0


$$\hat a_v= x_1u_1+\dots+x_ru_r$$
$$\{u_i\}\in\mathbb R^{m_v}$$
$$m_v = |G_p|$$

$$\hat{\mathbf{C}}\ \mathbf y = (0,\dots,0,1)^T$$
$$\mathbf{y}:=(x_1,\ \dots\ ,\ x_r,\ K)$$
$$\hat{\mathbf C}=\left(\frac{C}{1^{T}}\frac{-1}{0}\right)$$
$$C=(c_{st})_{s,t} \quad\text{ is }\quad r\times r$$

$$c_{st}:=\sum_{p=1}^n\langle W^\prime_{vp} u_s- \lambda^\prime_{vp} u_s,\ W^\prime_{vp} u_t- \lambda^\prime_{vp} u_t\rangle$$

A solution that is not restricted to a particular subspace is obtained when $r = m_v$ and $u_1,\dots, u_{m_v}$ is the canonical basis of $\mathbb R^{m_v}$. This solution is the one with the smallest error.

## Reduction Vectors

In [14]:
function get_standard_basis_vectors(dimension)
    canonical_basis = Diagonal(ones(dimension))
    return canonical_basis[:, 1:dimension]
end

u1 = get_standard_basis_vectors(13)
u2 = get_standard_basis_vectors(12)
u3 = get_standard_basis_vectors(6)

6×6 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0

$$\hat C = \begin{pmatrix} C & \mathbf{1} \\ \mathbf{1}^T & 0 \end{pmatrix}$$

$$\mathbf{\hat{C} y} =(0,\dots,0, 1)$$
$$\mathbf y =(x_1,\dots,x_r, K)$$

In [15]:
# CLUSTER 1
# v = 1
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t
r1 = g1_dim[1]
C1 = zeros(r1, r1)  # Initialize the matrix C

for i in 1:r1
    for j in 1:r1
        term1 = dot(W11p * u1[:, i] - λ11 * u1[:, i], W11p * u1[:, j] - λ11 * u1[:, j])
        term2 = dot(W12p * u1[:, i] - λ12 * u1[:, i], W12p * u1[:, j] - λ12 * u1[:, j])
        term3 = dot(W13p * u1[:, i] - λ13 * u1[:, i], W13p * u1[:, j] - λ13 * u1[:, j])
        C1[i, j] = term1 + term2 + term3
    end
end

ones_col = ones(size(C1, 1))  
ones_row = ones(1, size(C1, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C1, ones_col)  
C1_hat = vcat(top_row, ones_row)  

C1_hat

14×14 Matrix{Float64}:
 16.699    -6.84075  -6.84075  -6.84075  …   0.0       0.0       0.0      1.0
 -6.84075  14.699     1.0       1.0          0.0       0.0       1.0      1.0
 -6.84075   1.0      14.699     1.0          1.0       1.0       1.0      1.0
 -6.84075   1.0       1.0      14.699        1.0       1.0       1.0      1.0
 -6.84075   1.0       1.0       1.0          0.0       1.0       1.0      1.0
  1.0      -6.84075   0.0       0.0      …   0.0       0.0      -6.84075  1.0
  1.0       0.0      -6.84075   0.0         -6.84075  -6.84075  -6.84075  1.0
  1.0       0.0       0.0      -6.84075     -6.84075  -6.84075  -6.84075  1.0
  1.0       0.0       0.0       0.0          0.0      -6.84075  -6.84075  1.0
  0.0       1.0       1.0       1.0          2.0       2.0       3.0      1.0
  0.0       0.0       1.0       1.0      …  13.699     2.0       2.0      1.0
  0.0       0.0       1.0       1.0          2.0      14.699     3.0      1.0
  0.0       1.0       1.0       1.0      

In [16]:
rhs = zeros(size(C1_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C1_hat \ rhs

coefficients = y[1:r1]  

a1 = u1 * coefficients

print(a1)
sum(a1)

[0.03671660968145352, 0.030152989162889714, 0.04588827469461988, 0.04588827469461992, 0.02579935605039592, 0.07619576963732412, 0.133959230709688, 0.13395923070968804, 0.06678655972904103, 0.10352631181188926, 0.08078773725113474, 0.09880054065325064, 0.12153911521400514]

0.9999999999999999

In [17]:
# CLUSTER 2
# v = 2
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t
r2 = g2_dim[1]
C2 = zeros(r2, r2)  # Initialize the matrix C

for i in 1:r2
    for j in 1:r2
        term1 = dot(W21p * u2[:, i] - λ21 * u2[:, i], W21p * u2[:, j] - λ21 * u2[:, j])
        term2 = dot(W22p * u2[:, i] - λ22 * u2[:, i], W22p * u2[:, j] - λ22 * u2[:, j])
        term3 = dot(W23p * u2[:, i] - λ23 * u2[:, i], W23p * u2[:, j] - λ23 * u2[:, j])
        C2[i, j] = term1 + term2 + term3
    end
end
ones_col = ones(size(C2, 1))  
ones_row = ones(1, size(C2, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C2, ones_col)  
C2_hat = vcat(top_row, ones_row)  

C2_hat

13×13 Matrix{Float64}:
 25.0429    0.0       0.0       0.0      …   0.0       1.0       0.0      1.0
  0.0      28.0429    3.0       4.0          4.0      -9.38998  -9.38998  1.0
  0.0       3.0      26.0429    3.0          2.0      -9.38998   0.0      1.0
  0.0       4.0       3.0      27.0429       3.0      -9.38998  -9.38998  1.0
  0.0       5.0       3.0       4.0          4.0      -9.38998  -9.38998  1.0
  1.0      -9.38998   0.0       0.0      …  -9.38998   3.0       3.0      1.0
  1.0      -9.38998  -9.38998  -9.38998     -9.38998   5.0       4.0      1.0
  1.0      -9.38998  -9.38998  -9.38998     -9.38998   5.0       4.0      1.0
 -9.38998   4.0       3.0       3.0          3.0      -9.38998   0.0      1.0
  0.0       4.0       2.0       3.0         28.0429    0.0      -9.38998  1.0
  1.0      -9.38998  -9.38998  -9.38998  …   0.0      28.0429    3.0      1.0
  0.0      -9.38998   0.0      -9.38998     -9.38998   3.0      27.0429   1.0
  1.0       1.0       1.0       1.0      

In [18]:
rhs = zeros(size(C2_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C2_hat \ rhs

coefficients = y[1:r2]  

a2 = u2 * coefficients
print(a2)
sum(a2)

[0.02035349511022526, 0.09977868897224149, 0.06783438480777043, 0.08393947034618121, 0.09977868897224149, 0.07735859273308107, 0.10881686468603428, 0.10881686468603428, 0.08462283912442876, 0.07723338652758573, 0.09352847281481348, 0.0779382512193626]

1.0

In [19]:
# CLUSTER 3
# v = 3
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t

r3 = g3_dim[1]
C3 = zeros(r3, r3) 

for i in 1:r3
    for j in 1:r3
        term1 = dot(W31p * u3[:, i] - λ31 * u3[:, i], W31p * u3[:, j] - λ31 * u3[:, j])
        term2 = dot(W32p * u3[:, i] - λ32 * u3[:, i], W32p * u3[:, j] - λ32 * u3[:, j])
        term3 = dot(W33p * u3[:, i] - λ33 * u3[:, i], W33p * u3[:, j] - λ33 * u3[:, j])
        C3[i, j] = term1 + term2 + term3
    end
end

ones_col = ones(size(C3, 1))  
ones_row = ones(1, size(C3, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C3, ones_col)  
C3_hat = vcat(top_row, ones_row)  

C3_hat

7×7 Matrix{Float64}:
  9.34017  -4.41855   1.0       1.0      -4.41855   1.0      1.0
 -4.41855  10.3402    1.0       1.0      -4.41855   1.0      1.0
  1.0       1.0       9.34017  -4.41855  -4.41855   1.0      1.0
  1.0       1.0      -4.41855  10.3402   -4.41855   1.0      1.0
 -4.41855  -4.41855  -4.41855  -4.41855  13.3402   -5.41855  1.0
  1.0       1.0       1.0       1.0      -5.41855   9.34017  1.0
  1.0       1.0       1.0       1.0       1.0       1.0      0.0

In [20]:
rhs = zeros(size(C3_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C3_hat \ rhs

coefficients = y[1:r3]  

a3 = u3 * coefficients

print(a3)
sum(a3)

[0.16603628392086836, 0.15478624039512281, 0.1660362839208683, 0.1547862403951228, 0.26152492610732053, 0.09683002526069712]

0.9999999999999998

## Compute $\mu_{vp}$ for every $p$

$$\mu_{vp}=\frac{a_v^T K_{vp}a_v}{||a_v||^2}$$

In [21]:
mu11 = dot(a1', K11, a1) / dot(a1, a1)
mu22 = dot(a2', K22, a2) / dot(a2, a2)
mu33 = dot(a3', K33, a3) / dot(a3, a3)

println("μ₁₁: ", mu11)
println("μ₂₂: ", mu22)
println("μ₃₃: ", mu33)

μ₁₁: 3.795082313881939
μ₂₂: 4.863291524591332
μ₃₃: 3.0828691335884217


In [34]:
mu12 = dot(a1', K12, a1) / dot(a1, a1)
mu13 = dot(a1', K13, a1) / dot(a1, a1)
mu14 = dot(a1', K14, a1) / dot(a1, a1)
mu15 = dot(a1', K15, a1) / dot(a1, a1)
mu16 = dot(a1', K16, a1) / dot(a1, a1)
mu17 = dot(a1', K17, a1) / dot(a1, a1)
mu18 = dot(a1', K18, a1) / dot(a1, a1)
mu19 = dot(a1', K19, a1) / dot(a1, a1)
mu110 = dot(a1', K110, a1) / dot(a1, a1)
mu111 = dot(a1', K111, a1) / dot(a1, a1)
mu112 = dot(a1', K112, a1) / dot(a1, a1)
mu113 = dot(a1', K113, a1) / dot(a1, a1)

0.4855069947513862

In [38]:
mu21 = dot(a2', K21, a2) / dot(a2, a2)
mu22 = dot(a2', K22, a2) / dot(a2, a2)
mu23 = dot(a2', K23, a2) / dot(a2, a2)
mu24 = dot(a2', K24, a2) / dot(a2, a2)
mu25 = dot(a2', K25, a2) / dot(a2, a2)
mu26 = dot(a2', K26, a2) / dot(a2, a2)
mu27 = dot(a2', K27, a2) / dot(a2, a2)
mu28 = dot(a2', K28, a2) / dot(a2, a2)
mu29 = dot(a2', K29, a2) / dot(a2, a2)
mu210 = dot(a2', K210, a2) / dot(a2, a2)
mu211 = dot(a2', K211, a2) / dot(a2, a2)
mu212 = dot(a2', K212, a2) / dot(a2, a2)

0.3674879297648525

In [39]:
mu31 = dot(a3', K31, a3) / dot(a3, a3)
mu32 = dot(a3', K32, a3) / dot(a3, a3)
mu33 = dot(a3', K33, a3) / dot(a3, a3)
mu34 = dot(a3', K34, a3) / dot(a3, a3)
mu35 = dot(a3', K35, a3) / dot(a3, a3)
mu36 = dot(a3', K36, a3) / dot(a3, a3)

0.3782402231662288