In [1]:
using MAT
using LinearAlgebra

# Step 1: Identification of modules

First, we load the precomputed matrices from MATLAB.

In [2]:
adjacency_file = matopen("./matrices/weighted/S.mat")
cluster1_file = matopen("./matrices/weighted/S1.mat")
cluster2_file = matopen("./matrices/weighted/S2.mat")
cluster3_file = matopen("./matrices/weighted/S3.mat")

S = read(adjacency_file, "S")
println(issymmetric(S))

G1 = read(cluster1_file, "S1")
G2 = read(cluster2_file, "S2")
G3 = read(cluster3_file, "S3")

s_dim = size(S)
g1_dim = size(G1)
g2_dim = size(G2)
g3_dim = size(G3)

println("Matrix dimensions:")
println("\t[S] Adjacency matrix: ", s_dim)
println("\t[G1] Cluster 1: ", g1_dim)
println("\t[G2] Cluster 2: ", g2_dim)
println("\t[G3] Cluster 3: ", g3_dim)

true
Matrix dimensions:
	[S] Adjacency matrix: (31, 31)
	[G1] Cluster 1: (13, 13)
	[G2] Cluster 2: (12, 12)
	[G3] Cluster 3: (6, 6)


In [3]:
G1

13×13 Matrix{Float64}:
     0.0   10000.0  10000.0  1317.76  …  0.0        0.0     0.0
 10000.0       0.0      0.0     0.0      0.0        0.0     0.0
 10000.0       0.0      0.0     0.0      0.0        0.0     0.0
  1317.76      0.0      0.0     0.0      0.0        0.0     0.0
  1317.76      0.0      0.0     0.0      0.0        0.0     0.0
     0.0      60.0      0.0     0.0   …  0.0        0.0     0.189024
     0.0       0.0     60.0     0.0      2.5      278.205   0.050641
     0.0       0.0      0.0    60.0      3.19756   31.9632  0.0847458
     0.0       0.0      0.0     0.0      0.0       82.7381  0.169492
     0.0       0.0      0.0     0.0      0.0        0.0     0.0
     0.0       0.0      0.0     0.0   …  0.0        0.0     0.0
     0.0       0.0      0.0     0.0      0.0        0.0     0.0
     0.0       0.0      0.0     0.0      0.0        0.0     0.0

In [4]:
G2

12×12 Matrix{Float64}:
  0.0     0.0      0.0       0.0     …      0.0       0.0       0.0
  0.0     0.0      0.0       0.0            0.0     849.421    80.0
  0.0     0.0      0.0       0.0            0.0      10.3704    0.0
  0.0     0.0      0.0       0.0            0.0     800.0     800.0
  0.0     0.0      0.0       0.0            0.0      26.0     431.177
  0.0  1000.0      0.0       0.0     …  10000.0       0.0       0.0
  0.0   800.0    250.0     278.205         28.9855    0.0       0.0
  0.0   509.849  319.756    31.9632     10000.0       0.0       0.0
 10.0     0.0      0.0       0.0            0.0     180.0       0.0
  0.0     0.0      0.0       0.0            0.0       0.0     180.0
  0.0   849.421   10.3704  800.0     …      0.0       0.0       0.0
  0.0    80.0      0.0     800.0          180.0       0.0       0.0

In [5]:
G3

6×6 Matrix{Float64}:
  0.0     70.0001   0.0      0.0     70.0117  0.0
 70.0001   0.0      0.0      0.0     70.0001  0.0
  0.0      0.0      0.0     70.0001  70.0001  0.0
  0.0      0.0     70.0001   0.0     70.0001  0.0
 70.0117  70.0001  70.0001  70.0001   0.0     0.014
  0.0      0.0      0.0      0.0      0.014   0.0

## Adjacency submatrices

$W_{vp}$ is the submatrix of size $m_v \times m_p$ consisting of all interactions from $G_p$ and $G_v$.

($m_i$ is the size of the cluster $i$)

$$W_{12}$$

In [6]:
row_start = g1_dim[1]+1
row_end = g1_dim[1] + g2_dim[1]
col_start = 1
col_end = g1_dim[2]
W12 = S[row_start:row_end, col_start:col_end]

12×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1
 0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{21}$$

In [7]:
row_start = 1
row_end = g1_dim[1]
col_start = g1_dim[2] + 1                            # Same column range as W12
col_end = col_start -1 + g2_dim[2]
W21 = S[row_start:row_end, col_start:col_end]

13×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.1  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [8]:
W12 == W21' # The matrix is symmetric, thus we only need the transpose.

true

$$W_{13}$$

In [9]:
row_start = g1_dim[1] + g2_dim[1] +1
row_end = g1_dim[1] + g2_dim[1] + g3_dim[1]
col_start = 1
col_end = g1_dim[2]
W13 = S[row_start:row_end, col_start:col_end]

6×13 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

$$W_{31}$$

In [10]:
W31 = Matrix(W13')
W31

13×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

$$W_{23}$$

In [11]:
row_start = g1_dim[1] + g2_dim[1] +1
row_end = g1_dim[1] + g2_dim[1] + g3_dim[1]
col_start = g1_dim[2]+1
col_end = g1_dim[2] + g2_dim[2]
W23  = S[row_start:row_end, col_start:col_end]

6×12 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  70.0001   0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0     70.0001
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0   0.0      0.0

$$W_{32}$$

In [12]:
W32 = Matrix(W23')
W32

12×6 Matrix{Float64}:
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
  0.0     0.0   0.0     0.0  0.0  0.0
 70.0001  0.0   0.0     0.0  0.0  0.0
  0.0     0.0  70.0001  0.0  0.0  0.0

## Diagonal in-degree submatrices 

$K_{vp}$ is the in-degree matrix of size $m_v \times m_v$ from $G_p$ to $G_v$.

$$K_{vp} = \text{diag}(k_{i_1}^p,\dots, k_{i_{m_v}}^p)$$
$k_i^p = \sum_{j\in G_p} w_{ij}$

$$K_{vp}$$

$$K_{11} = \sum_j w_{1j}$$

In [13]:
function compute_in_degree(W::Matrix)
    # Initialize an empty vector to store the sums of each column
    sums = zeros(size(W, 2))
    
    # Iterate over each column of W and calculate the sum
    for i in 1:size(W, 2)
        sums[i] = sum(W[:, i])
    end
    
    # Construct the diagonal matrix K using the computed sums
    K = Diagonal(sums)
    
    return K
end

compute_in_degree (generic function with 1 method)

In [14]:
K11 = compute_in_degree(G1)
K22 = compute_in_degree(G2)
K33 = compute_in_degree(G3)

6×6 Diagonal{Float64, Vector{Float64}}:
 140.012     ⋅      ⋅      ⋅      ⋅      ⋅ 
    ⋅     140.0     ⋅      ⋅      ⋅      ⋅ 
    ⋅        ⋅   140.0     ⋅      ⋅      ⋅ 
    ⋅        ⋅      ⋅   140.0     ⋅      ⋅ 
    ⋅        ⋅      ⋅      ⋅   280.026   ⋅ 
    ⋅        ⋅      ⋅      ⋅      ⋅     0.014

In [15]:
K11

13×13 Diagonal{Float64, Vector{Float64}}:
 22635.5       ⋅        ⋅       ⋅    …      ⋅    ⋅          ⋅      ⋅ 
      ⋅   10060.0       ⋅       ⋅           ⋅    ⋅          ⋅      ⋅ 
      ⋅        ⋅   10060.0      ⋅           ⋅    ⋅          ⋅      ⋅ 
      ⋅        ⋅        ⋅   1377.76         ⋅    ⋅          ⋅      ⋅ 
      ⋅        ⋅        ⋅       ⋅           ⋅    ⋅          ⋅      ⋅ 
      ⋅        ⋅        ⋅       ⋅    …      ⋅    ⋅          ⋅      ⋅ 
      ⋅        ⋅        ⋅       ⋅           ⋅    ⋅          ⋅      ⋅ 
      ⋅        ⋅        ⋅       ⋅           ⋅    ⋅          ⋅      ⋅ 
      ⋅        ⋅        ⋅       ⋅           ⋅    ⋅          ⋅      ⋅ 
      ⋅        ⋅        ⋅       ⋅       1013.1   ⋅          ⋅      ⋅ 
      ⋅        ⋅        ⋅       ⋅    …      ⋅   5.69756     ⋅      ⋅ 
      ⋅        ⋅        ⋅       ⋅           ⋅    ⋅       392.906   ⋅ 
      ⋅        ⋅        ⋅       ⋅           ⋅    ⋅          ⋅     0.493903

In [16]:
K22

12×12 Diagonal{Float64, Vector{Float64}}:
 10.0      ⋅       ⋅         ⋅    …       ⋅        ⋅       ⋅        ⋅ 
   ⋅   3239.27     ⋅         ⋅            ⋅        ⋅       ⋅        ⋅ 
   ⋅       ⋅    580.126      ⋅            ⋅        ⋅       ⋅        ⋅ 
   ⋅       ⋅       ⋅     1910.17          ⋅        ⋅       ⋅        ⋅ 
   ⋅       ⋅       ⋅         ⋅            ⋅        ⋅       ⋅        ⋅ 
   ⋅       ⋅       ⋅         ⋅    …       ⋅        ⋅       ⋅        ⋅ 
   ⋅       ⋅       ⋅         ⋅            ⋅        ⋅       ⋅        ⋅ 
   ⋅       ⋅       ⋅         ⋅            ⋅        ⋅       ⋅        ⋅ 
   ⋅       ⋅       ⋅         ⋅       20219.0       ⋅       ⋅        ⋅ 
   ⋅       ⋅       ⋅         ⋅            ⋅   20209.0      ⋅        ⋅ 
   ⋅       ⋅       ⋅         ⋅    …       ⋅        ⋅   1865.79      ⋅ 
   ⋅       ⋅       ⋅         ⋅            ⋅        ⋅       ⋅    1491.18

In [17]:
K33

6×6 Diagonal{Float64, Vector{Float64}}:
 140.012     ⋅      ⋅      ⋅      ⋅      ⋅ 
    ⋅     140.0     ⋅      ⋅      ⋅      ⋅ 
    ⋅        ⋅   140.0     ⋅      ⋅      ⋅ 
    ⋅        ⋅      ⋅   140.0     ⋅      ⋅ 
    ⋅        ⋅      ⋅      ⋅   280.026   ⋅ 
    ⋅        ⋅      ⋅      ⋅      ⋅     0.014

In [18]:
K12 = compute_in_degree(W12)
K13 = compute_in_degree(W13)
K23 = compute_in_degree(W23);

In [19]:
K21 = compute_in_degree(W21)
K31 = compute_in_degree(W31)
K32 = compute_in_degree(W32);

In [20]:
K21 == K12

false

In [21]:
K21

12×12 Diagonal{Float64, Vector{Float64}}:
 0.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅   0.1   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅   0.1   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅   0.1   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅   0.1   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅   0.1   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.1   ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.1   ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0   ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0   ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0   ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0

In [22]:
K12

13×13 Diagonal{Float64, Vector{Float64}}:
 0.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅   0.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅   0.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅   0.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅   0.0   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅   0.1   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.1   ⋅    ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.1   ⋅    ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.0   ⋅    ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.1   ⋅    ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.1   ⋅    ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.1   ⋅ 
  ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅    ⋅   0.1

In [23]:
println(sum(K21))
println(sum(K12))

0.7000004328086249
0.700000432808625


# Step 2: Construction of observables 

$$W_{vp}^\prime \hat a_v= \lambda_{vp}^\prime\hat a_p$$
we focus on fixed $v$, variable $p$.

$$W^\prime_{vp} = W^T_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad W^\prime_{vp} = W^T_{pv}W^T_{vp}\quad \text{ if }\quad v\ne p$$
$$\lambda^\prime_{vp} = \lambda_{pp}\quad \text{ if }\quad v=p\quad \text { or }\quad \lambda^\prime_{vp} = \lambda_{pv}\lambda_{vp}\quad \text{ if }\quad v\ne p$$

In [24]:
W11p = G1'
W12p = W12' * W21'
W21p = W21' * W12'
W13p = W13' * W31'
W31p = W31' * W13'
W22p = G2'
W23p = W23' * W32'
W32p = W32' * W23'
W33p= G3'

println(size(W11p))
println(size(W22p))
println(size(W33p))
println(size(W12p))
println(size(W21p))
println(size(W13p))
println(size(W31p))
println(size(W23p))
println(size(W32p))

(13, 13)
(12, 12)
(6, 6)
(13, 13)
(12, 12)
(13, 13)
(6, 6)
(12, 12)
(6, 6)


In [25]:
# Eigenvalues
λ11 = eigmax(G1)
λ22 = eigmax(G2)
λ33 = eigmax(G3)

λ12 = eigmax(W12p) * eigmax(W21p)
λ21 = λ12
λ13 = eigmax(W13p) * eigmax(W31p)
λ31 = λ13
λ23 = eigmax(W23p) * eigmax(W32p)
λ32 = λ23

println("λ₁₁: ", λ11)
println("λ₂₂: ", λ22)
println("λ₃₃: ", λ33)
println("λ₁₂: ", λ12)
println("λ₁₃: ", λ13)
println("λ₂₃: ", λ23)

λ₁₁: 14264.521608182711
λ₂₂: 20031.62257307984
λ₃₃: 179.31450299794622
λ₁₂: 0.00010000173124573948
λ₁₃: 0.0
λ₂₃: 2.401009604024009e7


$$\hat a_v= x_1u_1+\dots+x_ru_r$$
$$\{u_i\}\in\mathbb R^{m_v}$$
$$m_v = |G_p|$$

$$\hat{\mathbf{C}}\ \mathbf y = (0,\dots,0,1)^T$$
$$\mathbf{y}:=(x_1,\ \dots\ ,\ x_r,\ K)$$
$$\hat{\mathbf C}=\left(\frac{C}{1^{T}}\frac{-1}{0}\right)$$
$$C=(c_{st})_{s,t} \quad\text{ is }\quad r\times r$$

$$c_{st}:=\sum_{p=1}^n\langle W^\prime_{vp} u_s- \lambda^\prime_{vp} u_s,\ W^\prime_{vp} u_t- \lambda^\prime_{vp} u_t\rangle$$

A solution that is not restricted to a particular subspace is obtained when $r = m_v$ and $u_1,\dots, u_{m_v}$ is the canonical basis of $\mathbb R^{m_v}$. This solution is the one with the smallest error.

## Reduction Vectors

In [26]:
function get_standard_basis_vectors(dimension)
    canonical_basis = Diagonal(ones(dimension))
    return canonical_basis[:, 1:dimension]
end

u1 = get_standard_basis_vectors(13)
u2 = get_standard_basis_vectors(12)
u3 = get_standard_basis_vectors(6)

6×6 Matrix{Float64}:
 1.0  0.0  0.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  1.0  0.0
 0.0  0.0  0.0  0.0  0.0  1.0

$$\hat C = \begin{pmatrix} C & \mathbf{1} \\ \mathbf{1}^T & 0 \end{pmatrix}$$

$$\mathbf{\hat{C} y} =(0,\dots,0, 1)$$
$$\mathbf y =(x_1,\dots,x_r, K)$$

In [27]:
# CLUSTER 1
# v = 1
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t
r1 = g1_dim[1]
C1 = zeros(r1, r1)  # Initialize the matrix C

for i in 1:r1
    for j in 1:r1
        term1 = dot(W11p * u1[:, i] - λ11 * u1[:, i], W11p * u1[:, j] - λ11 * u1[:, j])
        term2 = dot(W12p * u1[:, i] - λ12 * u1[:, i], W12p * u1[:, j] - λ12 * u1[:, j])
        term3 = dot(W13p * u1[:, i] - λ13 * u1[:, i], W13p * u1[:, j] - λ13 * u1[:, j])
        C1[i, j] = term1 + term2 + term3
    end
end

ones_col = ones(size(C1, 1))  
ones_row = ones(1, size(C1, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C1, ones_col)  
C1_hat = vcat(top_row, ones_row)  

C1_hat

14×14 Matrix{Float64}:
      4.0695e8      -2.8529e8   …      0.0            0.0        1.0
     -2.8529e8       3.0348e8          0.0           11.3415     1.0
     -2.8529e8       1.0e8         16692.3            3.03846    1.0
     -3.75943e7      1.31776e7      1917.79           5.08475    1.0
     -3.75943e7      1.31776e7      4964.29          10.1695     1.0
 600000.0           -1.71174e6  …      0.0        -5392.68       1.0
 600000.0            0.0              -7.93693e6  -1444.74       1.0
  79065.4            0.0              -9.11879e5  -2417.72       1.0
  79065.4            0.0              -2.36044e6  -4835.43       1.0
      0.0        60000.0            2388.61         189.862      1.0
      0.0            0.0        …    797.717          0.397582   1.0
      0.0            0.0               2.03562e8     30.8207     1.0
      0.0           11.3415           30.8207         2.03477e8  1.0
      1.0            1.0               1.0            1.0        0.0

In [28]:
rhs = zeros(size(C1_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C1_hat \ rhs

coefficients = y[1:r1]  

a1 = u1 * coefficients

print(a1)
sum(a1)

[0.385530224742906, 0.27027690826970757, 0.2702768865569303, 0.035615926236600134, 0.03561592646509521, 0.0011425129500534132, 0.0011373509103628212, 0.0001498904633464222, 0.0001499447862288995, 8.078616336112932e-5, 2.3293178127767716e-7, 2.3387673865621684e-5, 2.1849760603172708e-8]

0.9999999999999996

In [29]:
# CLUSTER 2
# v = 2
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t
r2 = g2_dim[1]
C2 = zeros(r2, r2)  # Initialize the matrix C

for i in 1:r2
    for j in 1:r2
        term1 = dot(W21p * u2[:, i] - λ21 * u2[:, i], W21p * u2[:, j] - λ21 * u2[:, j])
        term2 = dot(W22p * u2[:, i] - λ22 * u2[:, i], W22p * u2[:, j] - λ22 * u2[:, j])
        term3 = dot(W23p * u2[:, i] - λ23 * u2[:, i], W23p * u2[:, j] - λ23 * u2[:, j])
        C2[i, j] = term1 + term2 + term3
    end
end
ones_col = ones(size(C2, 1))  
ones_row = ones(1, size(C2, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C2, ones_col)  
C2_hat = vcat(top_row, ones_row)  

C2_hat

13×13 Matrix{Float64}:
      5.76485e14       0.0         …  1800.0             0.0        1.0
      0.0              5.76485e14       -3.40306e7      -3.20506e6  1.0
      0.0         371836.0              -4.15471e5       0.0        1.0
      0.0              9.82397e5        -3.20506e7      -3.20506e7  1.0
      0.0         249698.0              -1.04164e6      -1.72744e7  1.0
 100000.0             -4.00632e7   …     2.65434e6       1.9615e6   1.0
    289.855           -3.20506e7         9.10042e5  293965.0        1.0
 100000.0             -2.04262e7         2.26197e6       1.8664e6   1.0
     -4.00632e5        1.52746e7        -7.21138e6       0.0        1.0
      0.0              1.51361e7         0.0            -7.21138e6  1.0
   1800.0             -3.40306e7   …     5.7625e14       7.19164e5  1.0
      0.0             -3.20506e6         7.19164e5       5.7625e14  1.0
      1.0              1.0               1.0             1.0        0.0

In [30]:
rhs = zeros(size(C2_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C2_hat \ rhs

coefficients = y[1:r2]  

a2 = u2 * coefficients
print(a2)
sum(a2)

[0.08332763868124778, 0.08332765240573163, 0.08332764099477667, 0.08332764917745504, 0.08332764174540415, 0.08332770243379803, 0.0833276460668375, 0.08332770074969431, 0.08332769490319504, 0.08332769485504703, 0.0833616699168262, 0.08336166806998659]

0.9999999999999999

In [31]:
# CLUSTER 3
# v = 3
# n = 3
# p = 1..3
# s = 1..r
# t = 1..t

r3 = g3_dim[1]
C3 = zeros(r3, r3) 

for i in 1:r3
    for j in 1:r3
        term1 = dot(W31p * u3[:, i] - λ31 * u3[:, i], W31p * u3[:, j] - λ31 * u3[:, j])
        term2 = dot(W32p * u3[:, i] - λ32 * u3[:, i], W32p * u3[:, j] - λ32 * u3[:, j])
        term3 = dot(W33p * u3[:, i] - λ33 * u3[:, i], W33p * u3[:, j] - λ33 * u3[:, j])
        C3[i, j] = term1 + term2 + term3
    end
end

ones_col = ones(size(C3, 1))  
ones_row = ones(1, size(C3, 2) + 1)  
ones_row[end] = 0

top_row = hcat(C3, ones_col)  
C3_hat = vcat(top_row, ones_row)  

C3_hat

7×7 Matrix{Float64}:
      5.76249e14  -20203.2         …  -20208.2          0.980163    1.0
 -20203.2              5.76485e14     -20203.2          0.980001    1.0
   4900.82          4900.01           -20204.0          0.980001    1.0
   4900.82          4900.01           -20204.0          0.980001    1.0
 -20208.2         -20203.2                 5.76485e14  -5.02081     1.0
      0.980163         0.980001    …      -5.02081      5.76485e14  1.0
      1.0              1.0                 1.0          1.0         0.0

In [32]:
rhs = zeros(size(C3_hat, 1))  
rhs[end] = 1.0

# Solve for y
y = C3_hat \ rhs

coefficients = y[1:r3]  

a3 = u3 * coefficients

print(a3)
sum(a3)

[0.1667120257625811, 0.16664398711729178, 0.1667120257625808, 0.16664398711729203, 0.16664398712897818, 0.16664398711127607]

0.9999999999999999

## Compute $\mu_{vp}$ for every $p$

$$\mu_{vp}=\frac{a_v^T K_{vp}a_v}{||a_v||^2}$$

In [33]:
mu11 = dot(a1, K11 * a1) / dot(a1, a1)
mu22 = dot(a2, K22 * a2) / dot(a2, a2)
mu33 = dot(a3, K33 * a3) / dot(a3, a3)

println("μ₁₁: ", mu11)
println("μ₂₂: ", mu22)
println("μ₃₃: ", mu33)

μ₁₁: 16273.465487425427
μ₂₂: 7800.653148254713
μ₃₃: 140.00867213154856


In [34]:
mu12 = dot(a1, K12, a1) / dot(a1, a1)
mu13 = dot(a1, K13, a1) / dot(a1, a1)
mu23 = dot(a2, K23, a2) / dot(a2, a2)

println("μ₁₂: ", mu12)
println("μ₁₃: ", mu13)
println("μ₂₃: ", mu23)

μ₁₂: 8.841868906761077e-7
μ₁₃: 0.0
μ₂₃: 11.674613405026601


In [35]:
mu21 = dot(a2, K21 * a2) / dot(a2, a2)
mu31 = dot(a3, K31 * a3) / dot(a3, a3)
mu32 = dot(a3, K32 * a3) / dot(a3, a3)

println("μ₂₁: ", mu21)
println("μ₃₁: ", mu31)
println("μ₃₂: ", mu32)

μ₂₁: 0.0583254283653529
μ₃₁: 0.0
μ₃₂: 23.34605808990502


In [36]:
mu_mat = [mu11 mu12 mu13; mu21 mu22 mu23; mu31 mu32 mu33]

3×3 Matrix{Float64}:
 16273.5           8.84187e-7    0.0
     0.0583254  7800.65         11.6746
     0.0          23.3461      140.009